# Prometheus Configuration for OMARINO EMS

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'omarino-ems'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Time Series Service
  - job_name: 'timeseries-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['timeseries-service:5001']
        labels:
          service: 'timeseries'
          language: 'csharp'

  # Forecast Service
  - job_name: 'forecast-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['forecast-service:8001']
        labels:
          service: 'forecast'
          language: 'python'

  # Optimize Service
  - job_name: 'optimize-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['optimize-service:8002']
        labels:
          service: 'optimize'
          language: 'python'

  # Scheduler Service
  - job_name: 'scheduler-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['scheduler-service:5003']
        labels:
          service: 'scheduler'
          language: 'csharp'

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: 'gateway'
          language: 'csharp'

  # PostgreSQL Exporter (optional - requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         service: 'postgres'

  # Redis Exporter (optional - requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #       labels:
  #         service: 'redis'

  # Node Exporter (optional - for host metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node'
